---
apiVersion: v1
kind: Namespace
metadata:
  name: tailwind-pos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailwind-pos
  namespace: tailwind-pos
spec:
  selector:
    matchLabels:
      app: tailwind-pos
  template:
    metadata:
      labels:
        app: tailwind-pos
    spec:
      containers:
        - name: tailwind-pos
          image: quay.io/kubealex/tailwind-pos:latest
---
apiVersion: v1
kind: Service
metadata:
  name: tailwind-pos
  namespace: tailwind-pos
spec:
  selector:
    app: tailwind-pos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tailwind-pos
  namespace: tailwind-pos
spec:
  subdomain: windguard-dashboard
  to:
    kind: Service
    name: tailwind-pos
  port:
    targetPort: 8080
