# repoURL: https://gitlab.consulting.redhat.com/rh126-demojam/windguard.git
repourl: https://github.com/kubealex/windguard.git
path: demo-environment-setup/ocp-resources/ocp-setup/gitops/operators

operators:
  - name: openshift-ai
  - name: openshift-virtualization
  - name: advanced-cluster-management
