kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: windguard-demo-dashboard
  namespace: windguard-demo
spec:
  subdomain: windguard-dashboard
  to:
    kind: Service
    name: windguard-demo-vm-http
  port:
    targetPort: http
