kind: Service
apiVersion: v1
metadata:
  name: node-red-nodeport
  namespace: windguard
spec:
  type: NodePort
  ports:
    - name: nodered-port
      nodePort: 31880
      port: 1880
      targetPort: 1880
      protocol: TCP
  selector:
    app: node-red
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: windguard
  namespace: windguard
spec:
  subdomain: windguard-dashboard
  to:
    kind: Service
    name: node-red-nodeport
  port:
    targetPort: 1880
